### ISSUE TITLE
Rebranding TODO Check

### ISSUE THREAD

**Issue by fewensa** [helix-bridge/helix-ui#845]
- [x] Deploy redirect page for helixbridge.app
- [x] Deploy app use domain app.helix.box
- [x] Redirect docs.helixbridge.app -> docs.helix.box
- [x] Redirect xtoken.box -> xtoken.helix.box
- [x] apollo.helixbridge.app -> apollo.helix.box
- [x] apollo-test.helixbridge.app -> apollo-test.helix.box
- [x] Deprecated testnet.helixbridge.app   -> testnet-app.helix.box
- [x] ipfs.helixbridge.app -> ipfs.helix.box
- [x] swap.helix.box
- [x] apollo.xtoken.box -> apollo-xtoken.helix.box
- [x] apollo.xtoken.box -> apollo-xtoken-test.helix.box
- [x] darwinia.xtoken.box -> bridge.darwinia.network
- [x] Deploy helix home helix.box

**Comment by fewensa** [comment]
related: https://github.com/helix-bridge/helix-ui/pull/844
